### ISSUE TITLE
test_ping.nim no longer works after PR #11

### ISSUE THREAD

**Issue by onqtam** [Tormund/news#13]
as the title says... I'm currently looking into it. Any help is welcome. The commit: 09af7f0d97e925cedd7ab35a38df42bc5441c726

**Comment by Tormund** [comment]
looks like this isssue on echo server side, https://github.com/c-smile/sciter-sdk/issues/77#issuecomment-385587096
so I changed url https://github.com/Tormund/news/commit/914f997a98129fb63a922d8487ab7fb7c8e77913
now it works
