### ISSUE TITLE
Problems since PR #11

### ISSUE THREAD

**Issue by onqtam** [Tormund/news#14]
So I've been experiencing failures in the test suite of https://github.com/status-im/nim-web3 and it's still related to #11 - the issue is this: https://github.com/Tormund/news/pull/11/files#diff-eb3659d626af1420802877067e8159c6R207 - we used to pass the `url` string but now we pass the `path` part of the parsed `uri` which in this case ends up being an empty string (the `url` passed to the whole function in my case is this: `ws://127.0.0.1:8545`). Not sure what the correct solution is...

**Comment by Tormund** [comment]
Yes this is issue, path can't be empty https://tools.ietf.org/html/rfc2616#section-5.1.2
Fixed in https://github.com/Tormund/news/commit/55d3214c57a880d31ac7542364820e07f8c8abe5
Thanks for report.

**Comment by onqtam** [comment]
Thanks for the expedient fix, yet again! Will test tomorrow.
