### ISSUE TITLE
Doesn't implement closing handshake

### ISSUE THREAD

**Issue by snej** [Tormund/news#15]
The implementation doesn't obey the WebSocket closing handshake protocol, described in [section 1.4 of the RFC](https://tools.ietf.org/html/rfc6455#section-1.4):

>   Either peer can send a control frame with data containing a specified
>   control sequence to begin the closing handshake (detailed in
>   Section 5.5.1).  Upon receiving such a frame, the other peer sends a
>   Close frame in response, if it hasn't already sent one.  Upon
>   receiving _that_ control frame, the first peer then closes the
>   connection, safe in the knowledge that no further data is
>   forthcoming.
>
>   After sending a control frame indicating the connection should be
>   closed, a peer does not send any further data; after receiving a
>   control frame indicating the connection should be closed, a peer
>   discards any further data received.

Specifically:
1. `close()` closes the connection immediately without going through the handshake. It should instead\* send a Close frame and wait for an incoming Close frame, before closing.
2.`receivePacket()` handles an incoming Close frame by calling `close()`. It should instead send an acknowledging Close frame, then close the connection.

\* It's still good to have a method that disconnects without going through the handshake, especially in cases where the server isn't responding and you don't want to wait 90 minutes for TCP to time out. Maybe call it `disconnect`, or maybe call the handshake close `closeRequest`...

Note that [section 5.1](https://tools.ietf.org/html/rfc6455#section-5.5.1) says the peer initiating the close can add a status code and message to the frame describing why it's closing; we've found this useful, so it would be good to support in the API.

**Comment by Tormund** [comment]
Thanks for report, will see at this in spare time.

**Comment by Tormund** [comment]
new proc `shutdown` to close connection with handshake
