### ISSUE TITLE
"Upgrade: webSocket" should be "Upgrade: websocket"

### ISSUE THREAD

**Issue by snej** [Tormund/news#16]
My existing WebSocket client cannot connect to a 'news' server, because the server response headers contain `Upgrade: webSocket`, not `Upgrade: websocket` as required by [the spec](https://tools.ietf.org/html/rfc6455#section-4.2.2):

       2.  An |Upgrade| header field with value "websocket" as per RFC
           2616 [RFC2616].

I've looked through the HTTP spec and can't find anything stating that the Upgrade header value is case-insensitive, so I believe 'news' is wrong here.

**Comment by Tormund** [comment]
Thanks for report!
